### ISSUE TITLE
Do not fail on empty directory

### ISSUE THREAD

**Issue by sobolevn** [willkg/dennis#106]
Currently I am working on this template: https://github.com/wemake-services/wemake-django-template

Which obviously do not have any translation files. And `dennis` fails like this:

```
dennis version 0.9
Usage: dennis-cmd lint [OPTIONS] [PATH]...
Error: nothing to work on. Use --help for help.
```
Link to the build: https://travis-ci.org/wemake-services/wemake-django-template/builds/519593285

Which is unfortunate. Could it please stick to the rule "no code = no errors"?

**Comment by willkg** [comment]
Seems like that's wrapped in a check for `.po` files, so there should be something for dennis to work on. Is the check not working right?

**Comment by willkg** [comment]
I think dennis is doing the right thing here, though I see how that's causing problems in wemake-django-template. In this case, dennis wasn't given any files to work on which is a usage issue and usage issues like this which often denote a problem should return a non-zero error code. If you accidentally passed it the wrong directory, you'd want it to tell you and not fail silently. Similarly, if you use `cp` without passing in files, it errors.

Wrapping it like you did seems like a good approach for handling your specific need! Might be a good thing to add to the recipes section of the docs.

**Comment by sobolevn** [comment]
This is my workaround for this case:

```bash
if find locale -name '*.po' -print0 | grep -q "."; then
    # Only executes when there is at least one `.po` file:
    dennis-cmd lint locale
fi
```
