### ISSUE TITLE
lint : rule exclusion/rule limiting

### ISSUE THREAD

**Issue by NotSqrt** [willkg/dennis#60]
I just tried ``dennis-cmd lint --rules E101,E102,E103,E201,W202,W301,W303,W500,W501,W502 file.po`` in a hope to ignore W302.

1. it failed because the first error codes are not recognized in dennis/templatelinter:convert_rules, and the last ones are not recognized in dennis/linter:convert_rules
2. a very userful alternative would be to provide a ``--exclude`` option.

Any hope of seeing something like that ?

**Comment by willkg** [comment]
I think there are two separate issues here.

1. the `--rules` argument doesn't work now that I've combined the linter and templatelinter and that should be fixed
2. you would like an `--exclude` argument

The first one definitely needs to be fixed. I created issue #61 for that.

I've seen other commands have include and exclude options, but I'm not wildly excited about that. It's not something I'll spend time coding. I'd entertain a PR if someone else was interested in figuring out the behavior and implementing it.

**Comment by NotSqrt** [comment]
Thanks.

If I am too annoyed by ``dennis-cmd lint | grep -v W302``, I'll look into the code.

**Comment by willkg** [comment]
I spent some time thinking about where I want Dennis to go and all futures involve more lint rules. More rules creates problems with rules specification which I think exacerbates the problem you're bringing up.

Given that, I implemented `--exlucderules` argument. It's in 90ab98da. See if that works for you. If not, let me know what would be better.

**Comment by NotSqrt** [comment]
Awesome !
Looks good to me !
