### ISSUE TITLE
msgid in msgstr after translate

### ISSUE THREAD

**Issue by streetdaddy** [willkg/dennis#62]
**Original:**

    msgid "booking.addDestination"
    msgstr "Add destination for a quote"

**Command:**

    dennis-cmd translate -p pirate extracted.dennis.po

**Expected Result:**

    msgid "booking.destinationRequired"
    msgstr "Add destination fer a quote arrRRRrrr❗"

 .... the same as if I did :

    echo "Add destination for a quote" | dennis-cmd translate -)

**Actual Result:**

    msgid "booking.destinationRequired"
    msgstr "bookin'.destinationRequir'd arrRRr❗"

Am I doing something wrong, or missing something in the command, or the format of the po file?

**Comment by willkg** [comment]
Something related to this recently came up in another issue and I asked the reporter to file a new issue if he was interested. He didn't file anything, so I'm guessing he wasn't interested or it's not a significant use case:

https://github.com/willkg/dennis/issues/55#issuecomment-70390795

The issue there was that the `msgid` field doesn't have the untranslated string which is what Dennis uses to translate:

http://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

Your example here looks similar to the one he reported with Zope. What system are you using to generate those `.po` files?

**Comment by streetdaddy** [comment]
Ah yes, good point ... I'm working with translations exported from crowdin.com, and then I converted them to `.po` files using an online converter that has used the key instead of the value ...

The json file I have is in this format:

`"some.key": "string value",`
`"other.key": "other string value",`

I'll have to work out how to get this converted to `.po` and maintain the keys.

**Comment by willkg** [comment]
Interesting. There are several comment fields for `.po` files. I'd stash it away in one of them. For example, Dennis uses extracted comments to stick dennis lint ignore notes:

http://dennis.readthedocs.org/en/latest/linting.html#skipping-rules-string-by-string

You could put your id values there.

**Comment by willkg** [comment]
Er, when I say "put your id values there", I don't mean "use the dennis lint rule skipping stuff". I mean "create an extracted comment with your id". Something like this:

```
#. crowdin-id: booking.addDestination
```

Or something like thiat.

**Comment by streetdaddy** [comment]
Thanks @willkg I'll give that a go.

**Comment by willkg** [comment]
I haven't heard anything in a while, so I'm assuming this worked out fine, so I'm closing this out.
