### ISSUE TITLE
Check for matching Sphinx documentation syntax

### ISSUE THREAD

**Issue by jayvdb** [willkg/dennis#81]
It would be nice if dennis was able to detect when Sphinx documentation strings are translated without retaining the syntax, similar to how `W303` checks that HTML syntax must match.

The most common mistakes are adding spaces (e.g. below), or translating keywords

```
:term:`Zip`
: term: `Zip`
```

**Comment by jayvdb** [comment]
I am going to attempt to build this one now.

**Comment by jayvdb** [comment]
One approach is to look for [reST roles](http://docutils.sourceforge.net/docs/ref/rst/roles.html) enclosed in colons and having backticks, which [Sphinx uses](http://www.sphinx-doc.org/en/stable/markup/inline.html) in the message, and require:

1. the same number of usages of each role appears in the translation
2. they are not modified unless the role name is whitelisted.

The core reST roles `emphasis`, `strong`, `subscript`, `superscript ` and `title-reference` would be whitelisted as they contain translatable strings, but `literal`, `code`, `math`, `pep-reference` and `rfc-reference` would not as their value will usually not be different in other languages. (comments in `code` and text in `math` being exceptions).

**Comment by willkg** [comment]
I don't think this is something I'm going to build, but it's a great candidate for a plugin. Implementing plugin infrastructure is covered in issue #9.

**Comment by willkg** [comment]
I'm going to close this out--it's not something we're going to do.
