### ISSUE TITLE
undo click pinning

### ISSUE THREAD

**Issue by willkg** [willkg/dennis#91]
Currently, we have click pinned to a specific version. We probably shouldn't. Probably good enough to do `click>=6`.

This needs some research, though. Click history is here:

http://click.pocoo.org/6/changelog/

**Comment by willkg** [comment]
Pretty sure this is fine. I'll do it in the next release.

**Comment by sils** [comment]
:tada: and our master builds are broken because of this, we can implement a workaround but would like to see this fixed soon or we probably can't afford supporting dennis in coala :/

**Comment by sils** [comment]
though tbh pip could have been a little smarter and resolved the dependencies correctly...

**Comment by willkg** [comment]
Fixed in 033d88d.
